### ISSUE TITLE
runit support

### ISSUE THREAD

**Issue by 9glenda** [m-bdf/nixos-init-freedom#1]
First of all great project! Really good work!

I'd like to see support for other init systems like runit for example.

**Comment by m-bdf** [comment]
Hi, thanks for your interest!

Unfortunately this repo is a fork of [nixos-init-freedom](https://sr.ht/~guido/nixos-init-freedom), so all the credit goes to [Guido Witmond](https://sr.ht/~guido) (I probably should have made this clearer, sorry 😅). The only thing I've done in this copy is turn it into a flake and fix a small bug to make it work with my NixOS config (which it still doesn't, but I don't plan to work on it much more than that for now).

The project isn't quite complete and still has a few TODOs lying here and there, but no one seems to be working on it (last commit a year and a half ago), so I guess you're probably better off creating your own fork if you want to take over… I'd also suggest taking a look at [nix-processmgmt](https://github.com/svanderburg/nix-processmgmt), which looks promising (and a bit more active, though not so much recently).

That said, I'm closing this issue, have a nice day! ❤️

**Comment by 9glenda** [comment]
So does the flake support make it possible to pull this as a input from the flake? If that’s the case could you add an example of how to use this with a nixos config ad a flake in the readme?

**Comment by m-bdf** [comment]
Yep, I've updated the README with an example 👌

**Comment by 9glenda** [comment]
Thanks
